### ISSUE TITLE
the tests don't pass

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shenck0/py-leveldb#15]
```
~/dev/py-leveldb-read-only/test$ python -m unittest test
F....
======================================================================
FAIL: testIterationBasic (test.TestLevelDB)
testIterationBasic
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 134, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/utils.py", line 191, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "test.py", line 188, in testIterationBasic
    self._test_lowercase_iter(db)
  File "test.py", line 170, in _test_lowercase_iter
    self.assertEquals(s, 'mlkj')
  File "/usr/lib/python2.7/dist-packages/twisted/trial/unittest.py", line 270, in assertEqual
    % (msg, pformat(first), pformat(second)))
FailTest: not equal:
a = ''
b = 'mlkj'


----------------------------------------------------------------------
Ran 5 tests in 1.012s

FAILED (failures=1)

```

Original issue reported on code.google.com by `jtolds` on 24 May 2012 at 9:10

**Comment by GoogleCodeExporter** [comment]
Original comment by `arnim...@gmail.com` on 4 Jun 2012 at 5:55
- Changed state: **Fixed**
