### ISSUE TITLE
Installation requires ez_setup

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shenck0/py-leveldb#33]
```
Its no where documented that py-leveldb requires ez_setup for installation.

$ pip install leveldb
Downloading/unpacking leveldb
  Running setup.py egg_info for package leveldb
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/Users/vkapoor/.virtualenvs/test/build/leveldb/setup.py", line 14, in <module>
        import ez_setup
    ImportError: No module named ez_setup
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/Users/vkapoor/.virtualenvs/test/build/leveldb/setup.py", line 14, in <module>

    import ez_setup

ImportError: No module named ez_setup


This should be either clearly documented or the dependency should be removed.
```

Original issue reported on code.google.com by `kapoor.v...@gmail.com` on 9 Feb 2014 at 8:24

**Comment by GoogleCodeExporter** [comment]
```
ez_setup.py is not required anymore if you install from trunk, is it possible 
to get pypi release updated as requested by #32?.
```

Original comment by `dangra` on 6 Mar 2014 at 4:24

**Comment by GoogleCodeExporter** [comment]
```
I have the same issue, and it would be nice if I can get the fix in the version 
at pypi. I'm including py-leveldb in requirements.txt of my library as a 
dependency and "installing from trunk" won't fix in my case...
```

Original comment by `ksato9...@gmail.com` on 9 Mar 2014 at 12:22

**Comment by GoogleCodeExporter** [comment]
```
A ticked for this issue has been opened on gitbhub:

https://github.com/rjpower/py-leveldb/issues/3
```

Original comment by `legende2...@nexgo.de` on 28 Mar 2014 at 1:05
