### ISSUE TITLE
leveldb cannot be installed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shenck0/py-leveldb#34]
```
What steps will reproduce the problem?
1. run "pip install leveldb" from a fresh virtualenv.

What is the expected output? What do you see instead?

I would expect the package to be installed.

But installation bails out with:

Downloading/unpacking leveldb
  Downloading leveldb-0.192.tar.gz (225kB): 225kB downloaded
  Running setup.py (path:/home/t/py/build/leveldb/setup.py) egg_info for package leveldb
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/t/py/build/leveldb/setup.py", line 14, in <module>
        import ez_setup
    ImportError: No module named ez_setup
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/t/py/build/leveldb/setup.py", line 14, in <module>

    import ez_setup

ImportError: No module named ez_setup

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in 
/home/t/py/build/leveldb
Storing debug log for failure in /home/t/.pip/pip.log


What version of the product are you using? On what operating system?

debian 7.4, x86_64, python 2.7, pip 1.5.2

Please provide any additional information below.


```

Original issue reported on code.google.com by `schmir@gmail.com` on 19 Mar 2014 at 8:36

**Comment by GoogleCodeExporter** [comment]
```
pip install ez_setup
```

Original comment by `ZILIANGd...@gmail.com` on 25 Mar 2014 at 9:23

**Comment by GoogleCodeExporter** [comment]
```
Thanks for your suggestion.

That means I'll have to everyone to run "pip install ez_setup" before 
installing my package that depends on leveldb.

Sorry, but I don't understand why this hasn't been fixed in the recent release.

```

Original comment by `schmir@gmail.com` on 25 Mar 2014 at 10:12

**Comment by GoogleCodeExporter** [comment]
Original comment by `arnim...@gmail.com` on 25 Mar 2014 at 10:43
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
https://github.com/rjpower/py-leveldb/issues/3
```

Original comment by `legende2...@nexgo.de` on 28 Mar 2014 at 1:07
